# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

target 'Notify Me' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Notify Me
  pod 'FirebaseDatabase', :path => '/Users/vishal/firebase-ios-sdk'
  pod 'FirebaseCore', :path => '/Users/vishal/firebase-ios-sdk'
pod 'Material', '2.0.0'

end
